### ISSUE TITLE
两次滑动同一位置数据不一致

### ISSUE THREAD

**Issue by Glenn1Wang** [superSp/RulerView#3]
如最小设置为0，最大设置为10000000

**Comment by Glenn1Wang** [comment]
设置scalelimit无变化

**Comment by Glenn1Wang** [comment]
设置scalelimit后 最大最小值会扩大scalelimit倍

**Comment by superSp** [comment]
sccaleLimit的有意识相邻2个刻度之间的差值 例如默认为1  就是  1 2 3 4 ... 默认为2就是 1 3 5 7 9....我在模拟器上测试没发现问题。。
