### ISSUE TITLE
ScrollView嵌套的问题

### ISSUE THREAD

**Issue by weipeilong123** [superSp/RulerView#5]
外层套ScrollView+LinearLayout后，发生了高度wrap_content无效，高度直接填充了整个屏幕，需要怎么解决啊

**Comment by superSp** [comment]
刚刚看了下代码，有段代码位置放错了，需要替换一下
switch (heightModule) {
            case MeasureSpec.AT_MOST:
            case MeasureSpec.UNSPECIFIED:
                height = rulerHeight + (showScaleResult ? resultNumRect.height() : 0) + rulerToResultgap * 2 + getPaddingTop() + getPaddingBottom();
                break;
            case MeasureSpec.EXACTLY:
                height = heightSize + getPaddingTop() + getPaddingBottom();
                break;
        }
onMeasure中caseUNSPECIFIED放在和AT_MOST一起就可以了

**Comment by superSp** [comment]
1.5版本已经修复
