### ISSUE TITLE
这种可以实现???

### ISSUE THREAD

**Issue by lydlovexyz** [superSp/RulerView#6]
<img width="401" alt="微信截图_20190709151347" src="https://user-images.githubusercontent.com/19246347/60866951-47fd8a00-a25c-11e9-9257-d0be26204d67.png">

**Comment by lydlovexyz** [comment]
这里比短刻度稍微长一点点...

**Comment by superSp** [comment]
> 这里比短刻度稍微长一点点...

2个大刻度中间的一个刻度是默认比较长的，你的意思是，2个大刻度中间的刻度两边的刻度也要长一些吗？

**Comment by lydlovexyz** [comment]
<img width="376" alt="微信截图_20190710093408" src="https://user-images.githubusercontent.com/19246347/60933673-e853bd00-a2f5-11e9-9664-affa436258e1.png">

**Comment by lydlovexyz** [comment]
2个大刻度中间的一个刻度是默认比较长的,我的好像没有默认比较长.

**Comment by lydlovexyz** [comment]
背景如果是白色,圆角就隐藏了.

**Comment by lydlovexyz** [comment]
我们的设计图如下.

**Comment by lydlovexyz** [comment]
![添加血压](https://user-images.githubusercontent.com/19246347/60934083-7c725400-a2f7-11e9-91f2-22d78a945a92.png)

**Comment by superSp** [comment]
> 背景如果是白色,圆角就隐藏了.

这两个需求都不太具有普遍性。。。但是看起来都还算好改。。我待会儿单独发你一份吧

**Comment by lydlovexyz** [comment]
谢大佬!

**Comment by superSp** [comment]
> 谢大佬!
我直接发在你简书私信上吧

**Comment by superSp** [comment]
> 谢大佬!

太长了 发不过去。。。我的QQ 616391073  加我发给你吧
