### ISSUE TITLE
指定位置使用computeScrollTo 能不能去掉动画

### ISSUE THREAD

**Issue by cowoboy007** [superSp/RulerView#9]
指定位置使用computeScrollTo 能不能去掉动画，现在界面出来，会一下子滑动过去，体验比较差

**Comment by superSp** [comment]
你好，使用过firstScale这个属性吗？这个是默认刻度值，也就是尺子默认加载值，computeScrollTo 是指定跳转值

**Comment by cowoboy007** [comment]
用代码设置firstScale，是实际的10倍，没办法了我才用computeScrollTo

**Comment by superSp** [comment]
10倍？不太理解，要不贴一下布局代码  我看一下

**Comment by cowoboy007** [comment]
https://github.com/superSp/RulerView/issues/8,可以看下这个，和这个一样，比如设置16，界面会显示160

**Comment by superSp** [comment]
我刚刚按照那个布局设置 在oncreate中 rulerView.setFirstScale(58.0f)  还是没有复现bug。。

**Comment by cowoboy007** [comment]
<com.bbstrong.libui.edittext.RulerView
        android:id="@+id/rulerView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="30dp"
        android:layout_marginBottom="20dp"
        lsp:scaleLimit="10"
        lsp:bgColor="#fcfffc"
        lsp:firstScale="160"
        lsp:isBgRoundRect="false"
        lsp:largeScaleColor="@color/color_2fb9ff"
        lsp:largeScaleStroke="5dp"
        lsp:minScale="0"
        lsp:maxScale="250"
        lsp:midScaleColor="#999999"
        lsp:midScaleStroke="3dp"
        lsp:resultNumColor="@color/color_2fb9ff"
        lsp:resultNumTextSize="20sp"
        lsp:rulerHeight="50dp"
        lsp:rulerToResultgap="30dp"
        lsp:scaleCount="10"
        lsp:scaleGap="10dp"
        lsp:scaleNumColor="#666666"
        lsp:scaleNumTextSize="16sp"
        lsp:showScaleResult="true"
        lsp:smallScaleColor="#aaaaaa"
        lsp:smallScaleStroke="2dp"
        lsp:unit="cm"
        lsp:unitColor="@color/color_2fb9ff"
        lsp:unitTextSize="10sp"
        />
布局这么写，然后代码setFirstScale(16)，出来效果是160

**Comment by superSp** [comment]
我试一下

**Comment by superSp** [comment]
我试了还是没问题。。。 rulerView.setFirstScale(16F)   这里应该是16F吧  方法里面接收的是float类型

**Comment by cowoboy007** [comment]
怎么试，都是160.。。麻烦确认下之前别人提的问题吧。应该不是我一个人这样

**Comment by superSp** [comment]
> 怎么试，都是160.。。麻烦确认下之前别人提的问题吧。应该不是我一个人这样

嗯，有多个人提过肯定就是有问题了，不知道是不是布局还是其他问题，我这边不太好复现，等工作不忙了，我再试试

**Comment by auhah** [comment]
10倍这个问题是因为setMinScale setFirstScale setMaxScale三个方法和属性初始化时候的方法不一样，里面需要加 / scaleLimit 就正常了，但是实现还是不怎么友好。。
![image](https://user-images.githubusercontent.com/14848889/103336595-a7d09c00-4ab3-11eb-9a40-7729571efb80.png)
